"""

Revision ID: 3f9d644431d6
Revises: 
Create Date: 2022-07-24 21:47:21.179779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9d644431d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('another.anotherexamples',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('last_message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('another.anotherexamples')
    # ### end Alembic commands ###
